### PR TITLE
CONVO: Changes how SpecificBlock 'holds' on to its Tag.

### PR DESCRIPTION
**Pull request by drusellers**
This is a Conversational PR - the code almost compiles but not yet.

GOAL: Be lazy about getting the IWebElement to avoid Stale Reference Exceptions.

This was something that I've run into many times when dealing with Ajax heavy applications. To solve it we made our `Element`s only hold on to the `By` and then fetch it from the page each time. This was a perf hit, but in exchange our tess were significantly less brittle.

### CODE REVIEW

**Comment by drusellers** [comment]
@toddmeinershagen i'm closer now. The last step is to figure out how to best handle 'child' elements. Thoughts?

**Comment by chrisblock** [comment]
@drusellers, @toddmeinershagen: I think that the handling of child elements can be made fairly simple by having each `IBlock` keep track of its parent `IBlock` (and defering to the `IWebDriver` when the parent is not present) and then also storing the `By` object used to access it, as opposed to storing the `IWebElement` directly.

This would effectively merge the `SpecificBlock` and `Element` concepts (a distinction that seems largely unnecessary to me).

I have made a psuedo-code gist here: https://gist.github.com/chrisblock/788ba3487f18f417ede9

It is also important to note that doing this would require re-thinking of many (all?) of the usages of `Session.CurrentBlock<>` since it is difficult, at best, to capture the current context (parent) when using that method.

I also thought about introducing a specification pattern abstraction over the top of `By` for reduced coupling, as well as better composability and flexibility.

**Comment by toddmeinershagen** [comment]
@drusellers - I wanted @chrisblock to respond with his idea for handling child elements before I responded.  I like the way that he is handling the chain up through parent tags.  The only difference from your design is the storage of the By instead of a lambda.  

What are your thoughts on his design?

**Comment by drusellers** [comment]
@toddmeinershagen looking at the gist now. :)

**Comment by drusellers** [comment]
Ok, so I merged in with master so i am up to date. I have attempted to clean up the Element stuff per @chrisblock - i'm still looking at the child stuff. Need to get my head back in this space. I have a bunch of web testing that I'd love to use Bumblebee for. Thoughts on next steps Chris and Todd?

**Comment by chrisblock** [comment]
@drusellers I have also been working on this in a branch on my fork (https://github.com/chrisblock/Bumblebee/tree/stale). I would appreciate any feedback you might have.

What I have done is essentially remove `SpecificBlock` entirely, and make the `Element` class represent a user-interactable page element, with no children. I also broke the inheritance from `IBlock` to `Element` (e.g. `Element` does not inherit from `IBlock`), which means that `Element`s (`Clickable`s, `Checkbox`es, etc.) are not eligible for return from the various action methods `Element`s usally have (`Click`, `EnterText`, etc.).

I also followed through with making `IBlock`s have a `ParentBlock` property, and it seems to work pretty well.

I implemented a `BlockEnumerable<T>` that will create child blocks that lazily execute the enumerable of `IWebElement`s from the parent and index into it, which is a thing that I kind-of hate.

This leaves us closer to where I think we need to end up, but does leave a few weird situations about; specifically:
+   I think the `IAlertDialog` should not be an `IBlock` (it should have no parent)
+   the inheritance model is weird; there needs to be some other concept that could be thought of as `IReturnFromClickable`, but that is a truly terrible name for it
+   I believe that the correct way to fix the horribly inelegant index issue is to introduce our own specification pattern over the top of Selenium's `By`, and then to provide a concrete specification that does that indexing operation

**Comment by chrisblock** [comment]
Also of note is that I had to change the usages of the `Session.CurrentBlock<T>` method (which, as was not initially obvious to me, could actually only return a top-level `Block` or the `Element`'s parent, since that was the `IWebElement` passed in). I ended up creating a generic method, `FindRelated<T>` that will search the entire `Block` hierarchy for a `Block` of type `T` and return it.

Subsequently, `Session.CurrentBlock<T>` only works for `IBlock`s that have a constructor accepting only a `Session` (usually a `WebBlock`).

This makes me think that we may also need to introduce a `Page` abstraction, which in my mind would be akin to a parent-less block; e.g. it would need to be an `IReturnFromClickable` like the `IAlertDialog`, but also not actually an `IBlock`.

**Comment by drusellers** [comment]
the `Page` would map well to the Bumblebee docs as well about `Page` abstractions. I'm currently using `WebBlock`

**Comment by toddmeinershagen** [comment]
I have created a branch (stalefix) that we could use to keep merging together until we are ready to move it to the master.

Also, I have found some code on the Dev branch that might be working towards solving the issue we are working on.  You can find it [here](https://github.com/patrickherrmann/Bumblebee/commit/eaa11d73b0720bde9d08584e7093869bbd45d4d1).

**Comment by forcewake** [comment]
Hi @drusellers and @toddmeinershagen 
Do you have any updates on this feature? It looks like it can be interesting for a lot of developers.

**Comment by toddmeinershagen** [comment]
@drusellers We have released an alpha version of 2.0.0 for Bumblebee. This should address this issue. Please take a look and give us feedback.

**Pull request closed without merging**
