### PR TITLE
Add IFocusable interface with implementation and sample test

### PR DESCRIPTION
**Pull request by mateusz-dobrowolny**
OK, so I have "working" interface and added "proper" implementation

Some issues I encountered:
1. RadioButtons.cs is not a Block, so I had no possibility to call .focus() method on 'Tag'. That's why I set focus on RadioButton which is Selected.
2. Option.cs is being used both in SelectBox and RadioButtons, however in SelectBox browser does not allow to set focus on particular option (while for Radio Button - yes). So the usage of Option.cs class in both SelectBox and RadioButtons may require some review.

Please let me know what do you think.

### CODE REVIEW

**Comment by toddmeinershagen** [comment]
@mateusz-dobrowolny I haven't had time to review your changes yet, but I did get an email saying that your changes broke the build.  You might want to check [the results](https://ci.appveyor.com/project/toddmeinershagen/bumblebee/builds/24417665) out to see what happened.

**Comment by mateusz-dobrowolny** [comment]
Already fixed ;)
There was a typo :P

-----Wiadomość oryginalna-----
Od: "Todd Meinershagen" <notifications@github.com>
Wysłano: ‎2019-‎05-‎09 14:48
Do: "Bumblebee/Bumblebee" <Bumblebee@noreply.github.com>
DW: "mateusz-dobrowolny" <mateusz.dobrowolny@gmail.com>; "Mention" <mention@noreply.github.com>
Temat: Re: [Bumblebee/Bumblebee] Add IFocusable interface withimplementation and sample test (#131)

@mateusz-dobrowolny I haven't had time to review your changes yet, but I did get an email saying that your changes broke the build. You might want to check the results out to see what happened.

**Comment by toddmeinershagen** [comment]
@mateusz-dobrowolny Sorry, I have been a little busy as of late, so I am just getting around to reviewing this pull request.

I noticed that there is some code duplication for the SetFocus and HasFocus methods.  I am wondering what you think of putting that into two extension methods in the WebElementConvenience.cs and just calling those methods off of Tag.SetFocus() and Tag.HasFocus respectively in the associated methods.

**Comment by toddmeinershagen** [comment]
@mateusz-dobrowolny I also think you need to make sure to have better test coverage.  Instead of just verifying the RadioButtons, you also need to verify the SelectBox and at least one implementation of Element.

**Comment by toddmeinershagen** [comment]
@mateusz-dobrowolny I think you need to remove the ```SetFocus()``` in the ```Option``` class.  It is already implemented in the base ```Element``` class.  I think ```Click()``` (I am assuming you were using this for your reference) was only added there because ```Option``` version was different than the base version.  The testing will validate this as well.

**Pull request closed without merging**
